// Supabase Storage와 resources 테이블 연결 전 자료실 화면에서 사용하는 목업 데이터입니다.
import type { ResourceItem } from './resource.types';

export const mockResources: ResourceItem[] = [
  {
    id: 'resource-1',
    workspaceId: 'store-workspace',
    title: '7월 신메뉴 레시피.pdf',
    description: '망고라떼, 피치에이드 레시피',
    resourceType: 'file',
    fileName: '7월 신메뉴 레시피.pdf',
    uploadedBy: '김민서',
    createdAt: '2025-06-28',
  },
  {
    id: 'resource-2',
    workspaceId: 'store-workspace',
    title: '6월 매출 정산.xls',
    description: '일별 매출 집계표',
    resourceType: 'file',
    fileName: '6월 매출 정산.xlsx',
    uploadedBy: '이준혁',
    createdAt: '2025-06-30',
  },
  {
    id: 'resource-3',
    workspaceId: 'store-workspace',
    title: '재고 관리 시트',
    description: 'Google 스프레드시트',
    resourceType: 'link',
    linkProvider: 'link',
    url: 'https://docs.google.com/spreadsheets',
    uploadedBy: '김민서',
    createdAt: '2025-06-01',
  },
  {
    id: 'resource-4',
    workspaceId: 'store-workspace',
    title: '카드단말기 사용설명서.pdf',
    description: '신형 단말기 매뉴얼',
    resourceType: 'file',
    fileName: '카드단말기 사용설명서.pdf',
    uploadedBy: '이준혁',
    createdAt: '2025-06-22',
  },
  {
    id: 'resource-5',
    workspaceId: 'team-workspace',
    title: '캡스톤 기획서 v2.pdf',
    description: '최종 기획 문서',
    resourceType: 'file',
    fileName: '캡스톤 기획서 v2.pdf',
    uploadedBy: '김지은',
    createdAt: '2025-06-28',
  },
  {
    id: 'resource-6',
    workspaceId: 'team-workspace',
    title: 'Figma 디자인 파일',
    description: 'UI 컴포넌트 모음',
    resourceType: 'link',
    linkProvider: 'figma',
    url: 'https://figma.com',
    uploadedBy: '박서준',
    createdAt: '2025-06-26',
  },
  {
    id: 'resource-7',
    workspaceId: 'team-workspace',
    title: '사용자 인터뷰 결과.xlsx',
    description: '인터뷰 응답 원본 데이터',
    resourceType: 'file',
    fileName: '사용자 인터뷰 결과.xlsx',
    uploadedBy: '이하은',
    createdAt: '2025-06-24',
  },
  {
    id: 'resource-8',
    workspaceId: 'team-workspace',
    title: 'API 명세서 (Notion)',
    description: 'REST API 문서',
    resourceType: 'link',
    linkProvider: 'notion',
    url: 'https://notion.so',
    uploadedBy: '최민준',
    createdAt: '2025-06-22',
  },
  {
    id: 'resource-9',
    workspaceId: 'team-workspace',
    title: '로고 최종본.zip',
    description: 'PNG, SVG, AI 파일 포함',
    resourceType: 'file',
    fileName: '로고 최종본.zip',
    uploadedBy: '박서준',
    createdAt: '2025-06-20',
  },
  {
    id: 'resource-10',
    workspaceId: 'side-workspace',
    title: 'Fitto 피그마 파일',
    description: '전체 UI/X 디자인',
    resourceType: 'link',
    linkProvider: 'figma',
    url: 'http://figma.com',
    uploadedBy: '박서준',
    createdAt: '2025-06-30',
  },
  {
    id: 'resource-11',
    workspaceId: 'side-workspace',
    title: 'Github Repository',
    description: '매인 코드 저장소',
    resourceType: 'link',
    linkProvider: 'github',
    url: 'http://github.com',
    uploadedBy: '이하은',
    createdAt: '2025-06-31',
  },
  {
    id: 'resource-12',
    workspaceId: 'side-workspace',
    title: 'API 명세서 v3.pdf',
    description: 'REST API 전체 문제',
    resourceType: 'file',
    fileName: 'API 명세서 v3.pdf',
    uploadedBy: '이하은',
    createdAt: '2025-06-29',
  },
  {
    id: 'resource-13',
    workspaceId: 'side-workspace',
    title: '기획서_Fitto_v2.pdf',
    description: '서비스 기획 문서',
    resourceType: 'file',
    fileName: '기획서_Fitto_v2.pdf',
    uploadedBy: '김지은',
    createdAt: '2025-06-15',
  },
];
